Pine/docs/django_test/dtale_test/dtale_test/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create-df/', views.create_df, name='create-df'),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('ask/', AskView.as_view(), name='ask'),  # Class-Based View
]

djPine/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from pineproxy.views import TestProxyView,index, project, project_bot, stats_generating, help_index, help_iframe, home, getting_started, get_data_access,predict,predict_mlb_form_data,predict_nfl_form_data,predict_nfl_cbs_form_data,predict_nba_form_data, predict_nhl_form_data, activate_line_dataset,change_active_line_csv_status,predict_generating, predict_results, leaderboard, check_instance, analyze, prop_sheet, hr_sheet, anytime_td_sheet, thrive_sheet, pp_sheet, underdog_sheet, joke_sheet_tb, joke_sheet_nba, one_hundred_sheet, full_consistency_sheet, consistency_sheet, ps_sheet, discord_bot, prop_bet, bet_builder, get_book, model_score,ListDatafilesS3,health_check
from django.contrib.auth import views as auth_views

from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from users import views as users_views
from users.views import (
    logout,access_denied, save_changes,terms,privacy,activate_dataset,change_active_zip_status,
    activate,delete_charts,beta_user_random_str,beta_user,refresh_datasheets,set_access_beta_user,
    admin_sites,log_file_fetch, beta_code_admin_notification,user_invite_beta_user,invite_beta_status,
    no_data_access
    )

from users.views import FollowDoneView, UnFollowDoneView, user_sport_choice_add
from django.contrib.auth.decorators import login_required

#custom auth
from pineproxy.middlewares.auth import custom_auth_middleware
from blog.views import SearchListView
#Froala
from froala_editor import views
from blog.decorators import unauthenticated_user

urlpatterns = [
    #REST Data Endpoints
    path('data/', include('data.urls')),

    re_path(r'admin/?', admin.site.urls),
    re_path(r'notifications/?',include('notifications.urls')),
    path('', include('blog.urls',namespace='stories')),
    path('stats/<sport_name>/', index, name='stats'),
    path('stats/<sport_name>/Generating', stats_generating, name='stats_generating'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/<games_without_player>/', project, name='project'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/', project, name='project'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/', project, name='project'),

    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/<games_without_player>/', project_bot, name='project_bot'),
    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/', project_bot, name='project_bot'),
    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/', project_bot, name='project_bot'),

    path('stats/props/<sport_name>/', prop_sheet, name='props'),
    path('stats/props/<sport_name>/<sort>/', prop_sheet, name='props'),
    path('stats/NFL/TDs/', anytime_td_sheet, name='anytime_tds'),
    path('stats/NFL/TDs/<sort>/', anytime_td_sheet, name='anytime_tds'),
    path('stats/MLB/HRs/', hr_sheet, name='hrs'),
    path('stats/MLB/HRs/<sort>/', hr_sheet, name='hrs'),
    path('Thrive/<sport_name>/', thrive_sheet, name='thrive_props'),
    path('PrizePicks/<sport_name>/', pp_sheet, name='pp_props'),
    path('PrizePicks/<sport_name>/<sort>/', pp_sheet, name='pp_props'),
    path('Underdog/<sport_name>/', underdog_sheet, name='underdog_props'),
    path('Underdog/<sport_name>/<sort>/', underdog_sheet, name='underdog_props'),
    path('stats/analyze/<user_id>/<random_number>/', analyze, name='analyze'),
    path('check_instance/<instance_id>', check_instance, name='check_instance'),
    path('predict/<sport_name>/', predict, name='predict'),
    re_path(r'help/?', help_index, name='help'),
    path('predict/<sport_name>/<pt>/Generating', predict_generating, name='predict_generating'),
    path('predict/<sport_name>/<pt>', predict_results, name='predict_results'),
    path('predict/MLB/Building/Model', predict_mlb_form_data, name='predict_MLB'),
    path('predict/NFL/Building/Model', predict_nfl_form_data, name='predict_NFL'),
    path('predict/NFL-CBS/Building/Model', predict_nfl_cbs_form_data, name='predict_NFL_CBS'),
    path('predict/NBA/Building/Model', predict_nba_form_data, name='predict_NBA'),
    path('predict/NHL/Building/Model', predict_nhl_form_data, name='predict_NHL'),
    path('predict/<sport_name>/<pt>/Leaderboard', leaderboard, name='leaderboard'),
    path('predict/Model_Score/<sport_name>/<model_type>/', model_score, name='model_score'),
    path('predict/Model_Score/<sport_name>/<model_type>/<confidence_score>/', model_score, name='model_score'),
    path('help-iframe/', help_iframe, name='help-iframe'),
    re_path(r'home/?', home, name='home'),
    path('save-changes/<data_id>/', save_changes, name='save_as'),
    re_path(r'login/?', unauthenticated_user(auth_views.LoginView.as_view(template_name='users/login.html')), name='login'),
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    re_path(r'logout/?', logout, name='logout'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),
    path('generate_beta_code/', beta_user_random_str, name='beta_code'),
    path('beta_user/', beta_user, name='beta_user'),
    path('activate_dataset/', activate_dataset, name='activate_dataset'),
    path('settings/set_access_beta_user/', set_access_beta_user, name='set_access_beta_user'),
    path('settings/refresh_datasheets/', refresh_datasheets, name='refresh_datasheets'),
    path('change_active_zip_status/', change_active_zip_status, name='change_active_zip_status'),
    path('admin_sites/', admin_sites, name='admin_sites'),
    path('log_file/', log_file_fetch, name='log_file_fetch'),
    path('Joke/<prop>/', joke_sheet_nba, name='joke_sheet'),
    path('ParlayScience/<league>/', ps_sheet, name='ps_sheet'),
    path('ParlayScience/<league>/<game>/', ps_sheet, name='ps_sheet'),
    path('ParlayScience/<league>/<game>/<games_back>/', ps_sheet, name='ps_sheet'),
    path('ConsistencySheets/<league>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/<percent>/', consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/<percent>/<ou>/', consistency_sheet, name='consistency_sheet'),
    path('FullConsistencySheets/<league>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/<percent>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/<percent>/<ou>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('100Sheet/<league>/', one_hundred_sheet, name='one_hundred_sheet'),
    path('100Sheet/<league>/<ou>/', one_hundred_sheet, name='one_hundred_sheet'),
    path('Books/<book>', get_book, name="get_book"),
    path("DiscordBot/", discord_bot, name="discord_bot"),
    path("bet/<bet_id>", bet_builder, name="bet_builder"),
    path("prop-bet/<bet_id>", prop_bet, name="bet_builder"),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
     name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html'),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'),
     name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_complete"),

    re_path(r'register/?', users_views.register, name='register-users'),
    re_path(r'settings/?', users_views.profile, name='settings'),
    path('search-user/', users_views.SearchView, name='search_user'),
    path('search/', SearchListView.as_view(), name='search'),
    path('access_denied/', access_denied, name='access_denied'),
    path('settings/delete-chart-file/<name>/',delete_charts, name='delete_chart'),
    path('getting-started/',getting_started, name='getting_started'),
    path('get-data-access/',get_data_access, name='get_data_access'),
    #path('send-notification/', beta_code_admin_notification, name='admin_beta_notification'),
    path('send-invite-email/', user_invite_beta_user, name='user_beta_notification'),
    path('beta-user-status/', invite_beta_status, name='invite_beta_status'),
    path('activate_line_dataset/', activate_line_dataset, name='activate_line_dataset'),
    path('change_active_line_csv_status/', change_active_line_csv_status, name='change_active_line_csv_status'),
    # Follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnFollowDoneView.as_view()), name='unfollow_done_view'),
    path('delete_datafiles_s3/',ListDatafilesS3, name='delete_datafiles_s3'),
    #finds people who no data access
    path('no_data_access/', no_data_access, name='no_data_access'),

    path('prop-master/new/', users_views.prop_master_new, name='prop_master_new'), #screen1
    path('prop-master/invite/<str:uid>/', users_views.prop_master_invite, name='prop_master_invite'),
    path('prop-master/props/<str:uid>/', users_views.PropMaster_player2, name='prop_master_player2'),#screen2 player2 select props

payments/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from payments import views

app_name = 'payments'

urlpatterns = [
    path('', views.HomeView.as_view(), name='subscriptions_home'),
    path('create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('modify/confirm/<str:subscription_id>/create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('create-portal-session/', views.CreatePortalSessionView.as_view(), name='create_portal_session'),
    path('modify/confirm/<str:subscription_id>/create-portal-session/', views.CreatePortalSessionView.as_view(), name='create_portal_session'),
    path('discord/create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('success/', views.SuccessView.as_view(), name='subscriptions_success'),
    path('cancel/', views.CancelView.as_view(), name='subscriptions_cancel'),
    path('config/', views.stripe_config),
    path('webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('cancel-subscriptions/', views.cancel_subscription, name='cancel_subscription'),
    path('discordoauth', views.discord_oauth_callback, name='discord_oauth_callback'),
    path('discord/', views.DiscordSubscribeView.as_view(), name='discord_subscribe'),
    path('modify/confirm/<str:subscription_id>/', views.ModifyConfirmView.as_view(), name='modify_confirm'),
]

payments/models.py
from django.db import models
from django.contrib.auth.models import User


class StripeCustomer(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name="subuser")
    stripeCustomerId = models.CharField(max_length=255)
    stripeSubscriptionId = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

payments/templates/payments/cancel.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<head>
    
</head>

<div class="container pt-3">
    <p>You have cancelled the checkout.</p>
      <p><a href="{% url "payments:subscriptions_home" %}">Return to the dashboard</a></p>
</div>


{% endblock content %}

payments/templates/payments/home_discord.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>jaXon</title>
    <link rel="stylesheet" href="https://use.typekit.net/qau1euj.css" />
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-9DKFP5KMQ8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-9DKFP5KMQ8');
    </script>
    
    <script>
      var is_logged_in = {{ is_logged_in|yesno:"true,false" }};
      console.log("is_logged_in_frontend:", is_logged_in);
      var stripePublicKey = "{{ stripe_publishable_key }}";
      var username = "{{ username }}";  
      var plan_id = "{{ plan_id }}";
      var discord_username = "{{ discord_username }}";
      var subscription_canceled = "{{ subscription_canceled }}";
      

      //checkout variables

      // sandbox checkout vars

      
      var envurlbase = "{{ envurlbase }}";
      
      var essentialmonthlyid = "{{ essentialmonthlyid }}";
      var essentialyearlyid = "{{ essentialyearlyid }}";

      var premiummonthlyid = "{{ premiummonthlyid }}";
      var premiumyearlyid = "{{ premiumyearlyid }}";

      var ultimatemonthlyid = "{{ ultimatemonthlyid }}";
      var ultimateyearlyid = "{{ ultimateyearlyid }}";

      var premiumdiscordpriceid = "{{ premiumdiscordid }}";

      var success = discordOauthURl;
      var cancel = `${envurlbase}/subscribe/discord/`;

      var discordOauthURl = "{{ discordOAuthUrl|safe }}";

    
    </script>
  </head>
  <body>

    <header>
      <div class="header">
        <img src="{% static 'img/logo/jaxon-logo.svg' %}" alt="" />
        <div class="buttons">
          <a href="" class="btn" id="headerLogin"></a>
        </div>
      </div>
    </header>

    <section class="hero">
      <div class="hero-text">
        <!--<img src="{% static 'img/logo/jaxon-logo.svg' %}" width="250" alt="" />-->
        <img src="{% static 'img/discord-icon-svgrepo-com.svg' %}" width="200" alt="" />
        <h1>Smarter <span>Together</span></h1>
        <p>
        </p>
        <p>
        </p>
        <p>
        </p>
      </div>
      <div class="pricing-plan">
        <div class="cards">
          <div class="card first-card">
            <div class="card-top">
              <span class="card-title">FREE DISCORD</span>
              <p>
                Join the community to engage with the community.
              </p>
              <div class="monthly-price">
                <span class="new-price">$0.00 </span>
              </div>
              <a href="" class="btn subscriber" id="freediscord" style="background-color: #5865F2;">Join Now</a>
              
            </div>
            <div class="card-bottom">
              <ul>
                <li>
                  <img src="{% static 'img/checkmark.svg' %}" alt="" />
                  <p>Player Prop Research Tools - last 10 analysis and projections.
                  </p>
                </li>
                <li>
                  <img src="{% static 'img/checkmark.svg' %}" alt="" />
                  <p>Best Lines Research Tools - best prices on Moneyline, Spread, and Totals.</p>
                </li>
                <li>
                  <img src="{% static 'img/checkmark.svg' %}" alt="" />
                  <p>Instabet - add your fanduel sli screenshot to generate tailing links.</p>
                </li>
                <li>
                  <img src="{% static 'img/checkmark.svg' %}" alt="" />
                  <p>Bet Tracking - Connect your Discord to select sportsbooks, share bets and track plays.</p>
                </li>
              </ul>
            </div>
          </div>
          <div class="popular-card">
            <div class="popular-card-title">
              <span>EXTRA FEATURES</span>
            </div>
            <div class="card-border">
              <div class="card second-card">
                <div class="card-top">
                  <span class="card-title card-title-green">PREMIUM</span>
                  <p>
                    Get access to exclusive channels for arbs, middles, picks and JaXon tips.
                  </p>
                  <div class="monthly-price">
                    <span class="new-price">$19.99<span>/ mo</span> </span>
                  </div>
                  <a href="" class="btn btn-green subscriber" id="premiumdiscord">Subscribe</a>
                </div>
                <div class="card-bottom">
                  <ul>
                    <li>
                      <img src="{% static 'img/checkmark.svg' %}" alt="" />
                      <p>Everything in the Free Discord.</p>
                    </li>
                    <li>
                      <img src="{% static 'img/checkmark.svg' %}" alt="" />
                      <p>Daily Pinebot Picks - alerts from an enhanced preciction engine.</p>
                    </li>
                    <li>
                      <img src="{% static 'img/checkmark.svg' %}" alt="" />
                      <p>Arb & Middle Alerts - realtime alerts of guaranteed profit opportunities.</p>
                    </li>
                    <li>
                      <img src="{% static 'img/checkmark.svg' %}" alt="" />
                      <p>Plus EV Plays - mispriced bets on major sportsbooks and DFS providers.</p>
                    </li>
                    <li>
                      <img src="{% static 'img/checkmark.svg' %}" alt="" />
                      <p>Early access to betas, new features and product updates.</p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
         
        </div>
      </div>
    <div class="hero-bottom">
        <!--<p>
          You must make a free Pine Sports account to access the Premium Discord.
          <a href="https://www.pine-sports.com/register/?next=/subscribe/discord"
            >Register now!</a>
          
        </p>
        <p>
          Already have an account?
          <a href="https://www.pine-sports.com/login/?next=/subscribe/discord"
            >Log in here.</a>
          
        </p>-->
      </div>
    </section>

  


    <footer class="footer">
      <div class="footer-content">
        <div class="footer-top">
          <p>Copyright © 2024 Pine Sports Inc. | All Rights Reserved.</p>
          <ul>
           
            <li>
              <a href="https://x.com/PineSports_AI?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">
                <img src="{% static 'img/icon/twitter-icon.svg' %}" alt="" />
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/pine.sports/">
                <img src="{% static 'img/icon/instagram-icon.svg' %}" alt="" />
              </a>
            </li>
            
          </ul>
        </div>
        <div class="footer-bottom">
          <img src="{% static 'img/logo/jaxon-logo.svg' %}" alt="" />
          <ul class="footer-bottom-list">
            <li>
              <a href="/terms/">Terms Of Use</a>
            </li>
            <li>
              <a href="/privacy/">Privacy Policy</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

  
    <script>
       // Set the login url to logout for logged-in users
      
      // Check if user is logged in
    
    document.addEventListener('DOMContentLoaded', function() {
  // Check if user is logged in
  if (is_logged_in) {
    document.getElementById("headerLogin").innerHTML = "Logout";
    document.getElementById('headerLogin').setAttribute('href', '/logout/?next=/subscribe/discord/');
    // set the discord oauth url
    
    // Set the Stripe public key
    var stripe = Stripe(stripePublicKey);
    //console.log('Stripe initialized:', stripe);

    console.log("User is logged in. Setting subscription URLs for logged-in users.");

    const freediscord = document.getElementById('freediscord');

    freediscord.addEventListener('click', async function(e) {
          e.preventDefault();  // Prevent any immediate navigation
          setLoading();
          console.log('Redirecting to Discord');

          window.location.href = discordOauthURl;
        });

    const premiumdiscord = document.getElementById('premiumdiscord');
    premiumdiscord.addEventListener('click', async function(e) {
          e.preventDefault();  // Prevent any immediate navigation
          setLoading();
          console.log('Redirecting to Stripe');

          const id = this.id;
          //console.log('id:', id);

          try {
            const priceId = premiumdiscordpriceid;
            //console.log('priceId:', priceId);

            // Once priceId is successfully returned, proceed to Stripe Checkout
            fetch("create-checkout-session/", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },

            body: JSON.stringify({  id: priceId,success_url:discordOauthURl, cancel_url:cancel, free_trial_eligible: 'True'})

          })
          .then((result) => { return result.json(); })
            .then((data) => {
              if (data.error) {
                alert(data.error);
                window.location.reload();
              }
              // Redirect to Stripe Checkout
              return stripe.redirectToCheckout({sessionId: data.sessionId})
            })
            .then((data) => {
              // If redirectToCheckout fails due to a browser or network
              // error, you should display the localized error message to your
              // customer using error.message.
              if (data.error) {
                alert(data.error.message);
              }
            })
            .catch(function (error) {
              console.error("Error:", error);
            });
          } catch (error) {
            console.error('Error retrieving priceId or redirecting to checkout:', error);
            alert('Failed to get subscription details. Please try again.');
          }
        });
    
    
   
    
  } else {
    // For non-logged-in users
    console.log("User is not logged in. Setting subscription URLs for non-logged-in users.");
    document.getElementById('freediscord').setAttribute('href', '/login/?next=/subscribe/discord/');
    document.getElementById('premiumdiscord').setAttribute('href', '/login/?next=/subscribe/discord/');

    // Change login button
    document.getElementById("headerLogin").innerHTML = "Login";
    document.getElementById('headerLogin').setAttribute('href', '/login/');
  }
});

    

function setLoading() {
    const buttons = document.querySelectorAll('.btn');
    buttons.forEach((button) => {
      button.disabled = true;
    });
}

    </script>

  </body>
</html>

payments/templates/payments/success.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<head>
    
</head>

<div class="container pt-3">
    <p>You have successfully subscribed!</p>
    <p><a href="{% url "payments:subscriptions_home" %}">Return to the dashboard</a></p>    
</div>


{% endblock content %}