Pine/docs/django_test/dtale_test/dtale_test/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create-df/', views.create_df, name='create-df'),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('ask/', AskView.as_view(), name='ask'),  # Class-Based View
]

blog/urls.py
from django.urls import path
from django.urls import include, re_path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

from .views import (
    PostListView,
    PostListViewNew,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    UserDraftListView,
    FollowsListView,
    FollowersListView,
    postpreference,
    LikeView,
    SearchListView,
    postlikepreference,
    delete_comment,
    delete_comment_confirm,
    Like_comment,
    comment_postlikepreference,
    PostListViewFollowing,
    CommunityView,
    robots_txt,
    favicon_ico,
    last_post,
    generate_response,
    )

app_name = 'stories'

sitemaps = {
		"posts": PostSitemap,
}

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('new/', PostListViewNew.as_view(), name='blog-home-new'),
    path('following/', PostListViewFollowing.as_view(), name='blog-home-following'),
    path('community/<community_name>', CommunityView.as_view(), name='blog-community'),
    path('community/<community_name>/', CommunityView.as_view(), name='blog-community'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/<slug>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail-noslug'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('user/<str:username>/drafts/', UserDraftListView.as_view(), name='user-drafts'),
    path('post/<int:pk>/<slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/<slug>/del/', PostDeleteView.as_view(), name='post-delete'),
    path('user/<str:username>/follows', FollowsListView.as_view(), name='user-follows'),
    path('user/<str:username>/followers', FollowersListView.as_view(), name='user-followers'),
    path('post/<int:postid>/preference/<int:userpreference>', postpreference, name='postpreference'),
    path('like/<int:pk>',LikeView,name='like_post'),
    path('post/', postlikepreference, name='postlikepreference'),
    path('comment-post-like/', comment_postlikepreference, name='comment_postlikepreference'),
    re_path(r'^comment-delete/(?P<id>\w+)/', delete_comment, name='comment-delete'),
    path('like_comment/<int:id>',Like_comment, name='like_comment'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt", robots_txt),
    path("favicon.ico", favicon_ico),
    path("last_post.txt", last_post),
    path('generate_response/', generate_response, name='generate_response'),
]

djPine/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from pineproxy.views import TestProxyView,index, project, project_bot, stats_generating, help_index, help_iframe, home, getting_started, get_data_access,predict,predict_mlb_form_data,predict_nfl_form_data,predict_nfl_cbs_form_data,predict_nba_form_data, predict_nhl_form_data, activate_line_dataset,change_active_line_csv_status,predict_generating, predict_results, leaderboard, check_instance, analyze, prop_sheet, hr_sheet, anytime_td_sheet, thrive_sheet, pp_sheet, underdog_sheet, joke_sheet_tb, joke_sheet_nba, one_hundred_sheet, full_consistency_sheet, consistency_sheet, ps_sheet, discord_bot, prop_bet, bet_builder, get_book, model_score,ListDatafilesS3,health_check
from django.contrib.auth import views as auth_views

from django.views.static import serve

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from users import views as users_views
from users.views import (
    logout,access_denied, save_changes,terms,privacy,activate_dataset,change_active_zip_status,
    activate,delete_charts,beta_user_random_str,beta_user,refresh_datasheets,set_access_beta_user,
    admin_sites,log_file_fetch, beta_code_admin_notification,user_invite_beta_user,invite_beta_status,
    no_data_access
    )

from users.views import FollowDoneView, UnFollowDoneView, user_sport_choice_add
from django.contrib.auth.decorators import login_required

#custom auth
from pineproxy.middlewares.auth import custom_auth_middleware
from blog.views import SearchListView
#Froala
from froala_editor import views
from blog.decorators import unauthenticated_user

urlpatterns = [
    #REST Data Endpoints
    path('data/', include('data.urls')),

    re_path(r'admin/?', admin.site.urls),
    re_path(r'notifications/?',include('notifications.urls')),
    path('', include('blog.urls',namespace='stories')),
    path('stats/<sport_name>/', index, name='stats'),
    path('stats/<sport_name>/Generating', stats_generating, name='stats_generating'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/<games_without_player>/', project, name='project'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/', project, name='project'),
    path('stats/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/', project, name='project'),

    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/<games_without_player>/', project_bot, name='project_bot'),
    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/<split>/', project_bot, name='project_bot'),
    path('stats/bot/project/<sport_name>/<player_name>/<stat>/<prop>/<games_back>/', project_bot, name='project_bot'),

    path('stats/props/<sport_name>/', prop_sheet, name='props'),
    path('stats/props/<sport_name>/<sort>/', prop_sheet, name='props'),
    path('stats/NFL/TDs/', anytime_td_sheet, name='anytime_tds'),
    path('stats/NFL/TDs/<sort>/', anytime_td_sheet, name='anytime_tds'),
    path('stats/MLB/HRs/', hr_sheet, name='hrs'),
    path('stats/MLB/HRs/<sort>/', hr_sheet, name='hrs'),
    path('Thrive/<sport_name>/', thrive_sheet, name='thrive_props'),
    path('PrizePicks/<sport_name>/', pp_sheet, name='pp_props'),
    path('PrizePicks/<sport_name>/<sort>/', pp_sheet, name='pp_props'),
    path('Underdog/<sport_name>/', underdog_sheet, name='underdog_props'),
    path('Underdog/<sport_name>/<sort>/', underdog_sheet, name='underdog_props'),
    path('stats/analyze/<user_id>/<random_number>/', analyze, name='analyze'),
    path('check_instance/<instance_id>', check_instance, name='check_instance'),
    path('predict/<sport_name>/', predict, name='predict'),
    re_path(r'help/?', help_index, name='help'),
    path('predict/<sport_name>/<pt>/Generating', predict_generating, name='predict_generating'),
    path('predict/<sport_name>/<pt>', predict_results, name='predict_results'),
    path('predict/MLB/Building/Model', predict_mlb_form_data, name='predict_MLB'),
    path('predict/NFL/Building/Model', predict_nfl_form_data, name='predict_NFL'),
    path('predict/NFL-CBS/Building/Model', predict_nfl_cbs_form_data, name='predict_NFL_CBS'),
    path('predict/NBA/Building/Model', predict_nba_form_data, name='predict_NBA'),
    path('predict/NHL/Building/Model', predict_nhl_form_data, name='predict_NHL'),
    path('predict/<sport_name>/<pt>/Leaderboard', leaderboard, name='leaderboard'),
    path('predict/Model_Score/<sport_name>/<model_type>/', model_score, name='model_score'),
    path('predict/Model_Score/<sport_name>/<model_type>/<confidence_score>/', model_score, name='model_score'),
    path('help-iframe/', help_iframe, name='help-iframe'),
    re_path(r'home/?', home, name='home'),
    path('save-changes/<data_id>/', save_changes, name='save_as'),
    re_path(r'login/?', unauthenticated_user(auth_views.LoginView.as_view(template_name='users/login.html')), name='login'),
    path('activate/<uidb64>/<token>/',activate, name='activate'),
    re_path(r'logout/?', logout, name='logout'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),
    path('generate_beta_code/', beta_user_random_str, name='beta_code'),
    path('beta_user/', beta_user, name='beta_user'),
    path('activate_dataset/', activate_dataset, name='activate_dataset'),
    path('settings/set_access_beta_user/', set_access_beta_user, name='set_access_beta_user'),
    path('settings/refresh_datasheets/', refresh_datasheets, name='refresh_datasheets'),
    path('change_active_zip_status/', change_active_zip_status, name='change_active_zip_status'),
    path('admin_sites/', admin_sites, name='admin_sites'),
    path('log_file/', log_file_fetch, name='log_file_fetch'),
    path('Joke/<prop>/', joke_sheet_nba, name='joke_sheet'),
    path('ParlayScience/<league>/', ps_sheet, name='ps_sheet'),
    path('ParlayScience/<league>/<game>/', ps_sheet, name='ps_sheet'),
    path('ParlayScience/<league>/<game>/<games_back>/', ps_sheet, name='ps_sheet'),
    path('ConsistencySheets/<league>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/',  consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/<percent>/', consistency_sheet, name='consistency_sheet'),
    path('ConsistencySheets/<league>/<game>/<games_back>/<percent>/<ou>/', consistency_sheet, name='consistency_sheet'),
    path('FullConsistencySheets/<league>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/<percent>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('FullConsistencySheets/<league>/<games_back>/<percent>/<ou>/', full_consistency_sheet, name='full_consistency_sheet'),
    path('100Sheet/<league>/', one_hundred_sheet, name='one_hundred_sheet'),
    path('100Sheet/<league>/<ou>/', one_hundred_sheet, name='one_hundred_sheet'),
    path('Books/<book>', get_book, name="get_book"),
    path("DiscordBot/", discord_bot, name="discord_bot"),
    path("bet/<bet_id>", bet_builder, name="bet_builder"),
    path("prop-bet/<bet_id>", prop_bet, name="bet_builder"),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
     name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html'),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'),
     name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_complete"),

    re_path(r'register/?', users_views.register, name='register-users'),
    re_path(r'settings/?', users_views.profile, name='settings'),
    path('search-user/', users_views.SearchView, name='search_user'),
    path('search/', SearchListView.as_view(), name='search'),
    path('access_denied/', access_denied, name='access_denied'),
    path('settings/delete-chart-file/<name>/',delete_charts, name='delete_chart'),
    path('getting-started/',getting_started, name='getting_started'),
    path('get-data-access/',get_data_access, name='get_data_access'),
    #path('send-notification/', beta_code_admin_notification, name='admin_beta_notification'),
    path('send-invite-email/', user_invite_beta_user, name='user_beta_notification'),
    path('beta-user-status/', invite_beta_status, name='invite_beta_status'),
    path('activate_line_dataset/', activate_line_dataset, name='activate_line_dataset'),
    path('change_active_line_csv_status/', change_active_line_csv_status, name='change_active_line_csv_status'),
    # Follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnFollowDoneView.as_view()), name='unfollow_done_view'),
    path('delete_datafiles_s3/',ListDatafilesS3, name='delete_datafiles_s3'),
    #finds people who no data access
    path('no_data_access/', no_data_access, name='no_data_access'),

    path('prop-master/new/', users_views.prop_master_new, name='prop_master_new'), #screen1
    path('prop-master/invite/<str:uid>/', users_views.prop_master_invite, name='prop_master_invite'),
    path('prop-master/props/<str:uid>/', users_views.PropMaster_player2, name='prop_master_player2'),#screen2 player2 select props

blog/forms.py
from django import forms
from .models import Comment
from .models import Post, BlogSports
from froala_editor.widgets import FroalaEditor


class NewCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
            'content': FroalaEditor(options={
                'placeholderText': '  Add a comment.',
                'toolbarInline': True,
                'toolbarButtons': ['bold', 'italic', 'underline', '|', 'insertLink', 'insertImage'],
                'quickInsertTags': "null",
                'attribution': False,
                'charCounterCount': False,
                'heightMin': 40,
            }),
        }


class PostForm(forms.ModelForm):
    related_sport = forms.ModelChoiceField(queryset=BlogSports.objects.exclude(name='Pine News').order_by('name'), empty_label="Select a Sport")
    class Meta():
        model = Post
        fields = ('title','content','draft','related_sport')

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Your Title'}),
            'draft': forms.CheckboxInput(attrs={'class':'form-check-input ml-2','name':'draft_check','style':'visibility: hidden; display: none;'}),
            'content': FroalaEditor(options={

                #This activates inline mode
                #'toolbarInline': True,

                #This is a good inline toolbar
                #'toolbarButtons': ['bold', 'italic', 'underline', '|', 'outdent', 'indent', '|', 'formatOL', 'formatUL', '|','undo', 'redo'],

                #This defines what buttons are in the quick insert field (Plus sign with circle)
                #'quickInsertButtons': ['chart', 'image', 'video', 'table', 'ul', 'ol', 'hr'],

                # this pulls up the toolbar even if words are not highlighted (seems to get annoying)
                # 'toolbarVisibleWithoutSelection': True,

                # This is a good toolbar button if we decide against inline (html is added to debug). Defines for 2 screen sizes.
                'toolbarButtonsMD': ['bold', 'italic', 'underline', '|', 'alignLeft', 'alignCenter', 'alignRight', '|',
                                   'outdent', 'indent', '|', 'formatOL', 'insertLink', '|',
                                   'insertChart', 'insertImage', 'insertVideo', 'insertLink', '|', 'undo',
                                   'redo', 'html'],

                'toolbarButtonsSM': ['bold', 'italic', 'underline', '|', 'alignLeft', 'alignCenter', 'alignRight', '|',
                                   'outdent', 'indent', '|', 'formatOL', 'insertLink',
                                   'insertChart', 'insertImage', 'insertVideo', 'embedly','|', 'html'],

                'toolbarButtonsXS': ['bold', 'italic', 'underline', '-', 'insertChart', 'insertImage', 'insertVideo', 'embedly'],

                # This turns off the quick insert button
                'quickInsertTags': "null",

                #Turns off froala attribution
                'attribution': False,

                #Adds placeholder text
                'placeholderText': 'Tell us what you think. . . ',

                # This would be the max character count for a post.  The only issue is it displays at the bottom.
                #'charCounterMax': 5000,

                #Turns off character counter
                'charCounterCount': False,

                #Turns off video upload
                'videoUpload': False,

                #Only allows video by url, no embed or upload
                'videoInsertButtons': ['videoByURL'],

                #Removes image manager
                'imageInsertButtons': ['imageUpload', 'imageByURL'],

                # Removes text formatting when pasting content into the rich text editor, but keeps the content's structure.
                'pastePlain': True,
            }),
        }

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Blog Posts</h1>
{% endblock content %}

blog/templates/blog/hello.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<h1> Hello <b>{{user_id}}<b></h1>

{% endblock %}

blog/templates/blog/profile.html
{% extends "blog/base.html" %}
{% load static %}
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MVXEN40PGH"></script>
    <link rel="preload" href="{% static 'app-assets/css/colors.min.css' %}" as="style">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/colors.min.css' %}" media="print" onload="this.media='all'">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-185900750-1">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-185900750-1');
    </script>
</head>
<div class="col-12 col-md-3 pr-4 dont-move hidden pt-3">
    <!-- <a href="/"> <h2><img class="img-fluid" width="60" src="{% static 'blog/logo.png' %}">ReadyTweet</h2></a><br> -->
    <div class="profile-section">

        <h3 class="black-important p-2">
            Profile
        </h3>

        <article class="media content-section" style="height: 140px; width: 100%">
            {%  if user_profile != None %}
            <div class="mt-2 d-flex full-width align-items-center">
                <img
                        class="rounded-circle mr-3 img-fluid"
                        style="width: 90px; height: 90px;"
                        src="{{ user_profile.profile.image_url }}?v=2">
                <div>
                    <h4 style="text-align: left"
                        class="white-important">
                        {{ user_profile.username }}

                    </h4>
                    <h6 style="text-align: left"
                        class="email-profile">
                        {{ user.email }}

                    </h6>

                </div>
            </div>
            {%  else %}
            <div class="mt-2 d-flex full-width align-items-center">
                <img
                        class="rounded-circle mr-3"
                        style="width: 90px; height: 90px;"
                        src="{{ user.profile.image_url }}?v=2">
                <div>
                    <h4 style="text-align: left"
                        class="white-important">
                        {{ user.username }}
                    </h4>
                    <h6 style="text-align: left"
                        class="email-profile">
                        {{ user.email }}
                    </h6>
                </div>
            </div>
            {%  endif %}
        </article>
        <article class="media content-section">
            <div class="row full-width pl-2">
                <div class="col-6">
                    Followers
                </div>
                <div class="col-6">
                    Following
                </div>
                {%  if user_profile != None %}
                <div class="col-6">
                    <h3 class="white-important follow-click">
                        <a href="{% url 'stories:user-followers' user_profile.username %}">
                            {{ user_profile.profile.followers }}
                        </a>
                    </h3>
                </div>
                <div class="col-6">
                    <a href="{% url 'stories:user-follows' user_profile.username %}">
                        <h3 class="white-important follow-click">
                            {{ user_profile.profile.following }}
                        </h3>
                    </a>
                </div>
                {% else %}
                <div class="col-6">
                    <a href="{% url 'stories:user-followers' user.username %}">
                        <h3 class="white-important follow-click">
                            {{ user.profile.followers }}
                        </h3>
                    </a>
                </div>

                <a href="{% url 'stories:user-follows' user.username %}">
                    <div class="col-6">
                        <h3 class="white-important follow-click">
                            {{ user.profile.following }}
                        </h3>
                    </div>
                </a>
                {%  endif %}
            </div>
        </article>

        <div class="d-flex">
            {% if user_profile is None %}
            <div style="margin-left:25px">
                <a class="btn btn-sm btn-outline-primary mb-4 mr-3 " href="{% url 'stories:post-create' %}">
                    New Post
                </a>
            </div>
            {% endif %}
            {%  if user_profile is not None and user_profile.id != user.id  and user.username != '' %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <button style="margin-left: 18px" class="btn btn-sm btn-outline-primary"
                            name="{% if can_follow %}follow{% else %}unfollow{% endif %}"
                            type="submit">
                        {% if can_follow %}
                        FOLLOW
                        {% else %}
                        UNFOLLOW
                        {% endif %}
                    </button>
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>

blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}


<h3>Found {{page_obj.paginator.count}} post{{page_obj.paginator.count|pluralize}} with '{{search}}'</h1>
<br>
    <div class="row pt-3">
        
        <div class="col-12 col-md-1 dont-move"></div>
            <div class="col-12 col-md-10 scrollable" >
                {% for post in posts %}
                <article class="media content-section hovered-tweet">
                    <div style="width: 100%;">
                        
                        <div class="pb-2 row m-0" style="width: 100%; margin-right: 0 !important;">
                        <div
                                style="padding-left: 0px !important;"
                                class="col-8 no-padding d-flex align-items-center">
                            <img
                                class="rounded-circle mr-2"
                                style="width: 20px; height: 20px;"
                                src="{{ post.author.profile.image_url }}?v=2">
                            <a class="mr-2 white-important" href="{% url 'stories:user-posts' post.author %}">
                                {{ post.author }}
                                
                            </a>
                        </div>
                        <div class="col-4 d-flex flex-row-reverse no-padding align-items-center"
                                style="padding-right: 0 !important;">
                            {% if post.author == user %}
                                    <a class="material-icons ml-2"
                                    style="font-size: 14px"
                                            href="{% url 'stories:post-delete' post.id post.slug %}">clear</a>
                                    <a class="material-icons ml-2"
                                    style="font-size: 14px"
                                            href="{% url 'stories:post-update' post.id post.slug %}">update</a>
                                {%  endif %}
                        </div>
                        <br/>
                        {{ post.title }}
                    </div>
                        <div
                                class="mb-2"
                                style="width: 100%; height: 1px; background-color: rgba(255, 255, 255, 0.1)"></div>
                        <a
                                style="color: rgba(255, 255, 255, 0.5) !important;"
                                href="{% url 'stories:post-detail' post.id post.slug %}">
                            <p class="mb-4">
                                {% if post.content|safe|length < 100 %}
                                    {{ post.content|safe }}
                                {% else %}
                                    {{ post.content|safe|truncatewords_html:25 }}
                                    <a style="color: rgba(255, 255, 255, 0.5) !important;" href="{% url 'stories:post-detail' post.id post.slug %}">(continue reading)</a>
                                {% endif %}
                                
                                
                            </p>
                        </a>

                            <div class="row">
                                <div class="col-6" style="display: flex;" id="L-{{post.id}}">
                                    
                                    {% if request.user in post.likes.all %}
                                    <small  style="opacity: 0.4;cursor: pointer;">
                                        <a style="opacity: 0.4;"    onclick="return  likedislike( {{post.id}},'true');">
                                            <i style="color: red; font-size: 16px;" class="far fa-heart"></i> &nbsp{{post.likes.count}} like(s)
                                        </a>
                                        <!-- <form id="likebutton" method="POST" action="{% url 'stories:postpreference' post.id 1 %}">
                                        {% csrf_token %}
                                        <input type="hidden">
                                        </form> -->
                                        
                                    </small>
                                    {% else %}
                                    <small style="opacity: 0.4;cursor: pointer;"></small>
                                        <a style="opacity: 0.4;cursor: pointer;"  href="{% url 'login' %}">
                                            <i style=" font-size: 16px;" class="far fa-heart"></i> &nbsp{{post.likes.count}} like(s)
                                        </a>
                                    </small>
                                    {% endif %}
                                    <small style="opacity: 0.4; margin-left:15px;">
                                        <a href="{% url 'login' %}">
                                            <i style=" font-size: 16px;" class="far fa-comment"></i> {{ post.number_of_comments }} comment(s)
                                        </a>
                                        
                                    </small>
                                </div>
                                <div class="col-6">
                                    <small style="opacity: 0.4;"
                                        class="white-important d-flex full-width flex-row-reverse">
                                        {{ post.date_posted | date:"H:i l, d.m.y" }}
                                    </small>
                                </div>
                            </div>
                        
                    </div>
                </article>
                {% endfor %}
                
                <div class="full-width d-flex justify-content-center">
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <a class="btn btn-sm btn-outline-secondary mb-4 mr-2"
                                    href="?search={{search}}&page=1">First</a>
                            <a class="btn btn-sm btn-outline-secondary mb-4 mr-2"
                                    href="?search={{search}}&page={{ page_obj.previous_page_number }}">Previous</a>
                        {% endif %}
    
                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <a class="btn btn-sm btn-info mb-4 mr-2"
                                    href="?search={{search}}&page={{ num }}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <a class="btn btn-sm btn-outline-secondary mb-4 mr-2"
                                    href="?search={{search}}&page={{ num }}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}
    
                        {% if page_obj.has_next %}
                            <a class="btn btn-sm btn-outline-secondary mb-4 mr-2"
                                    href="?search={{search}}&page={{ page_obj.next_page_number }}">Next</a>
                               <a class="btn btn-sm btn-outline-secondary mb-4 mr-2"
                                href="?search={{search}}&page={{ page_obj.paginator.num_pages }}">Last</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
    </div>

    <div class="col-12 col-md-1 dont-move"></div>

    <p style="text-align:right;">
        <a href="">Terms</a>,
        <a href="">Privacy policy</a>,
        <a href="">Cookies</a>,
        <a href="">Ads info</a>,
        <a href="">More</a>
        © Pine,2020</p>
   
{% endblock %}

{% block script %}
<script type="text/javascript">
    function likedislike (id, value) {
        var id = id;
        var value = value;
        var url = "{% url 'stories:postlikepreference' %}";
        console.log(url);
        $.ajax({
        url: url,
        type: "GET",
        data: {
        
          "id": id,
          "value": value,
        //   "csrfmiddlewaretoken": "{{ csrf_token }}"

        },
        success: function (data) {
            console.log(data.html)
            var result = data.html;
            $('#L-'+id).html(result);
          
        }
      });

    }
</script>
{% endblock %}

blog/templates/blog/user_posts.html
{% extends "blog/home.html" %}
{% load static %}